---
# tasks file for marathon-lb

- name: run marathon-lb container
  docker_container:
    name: marathon-lb
    image: "{{ marathon_lb_image }}"
    state: started
    detach: true
    restart_policy: always
    network_mode: host
    command: "sse --marathon {{marathon_lb_marathon_url}} --group {{marathon_lb_group}} --auth-credentials={{marathon_lb_auth_creds}}"
    env: 
      PORTS: "{{marathon_lb_ports}}"
  tags: marathon-lb


- name: register marathon-lb with an http check
  consul:
    service_name: "marathon-lb-{{marathon_lb_group}}"
    service_address: "{{ansible_default_ipv4.address}}"
    service_port: 9090
    interval: 60s
    http: "http://{{ansible_default_ipv4.address}}:9090/_haproxy_health_check"
  tags: marathon-lb
